{{- if not .Values.models.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "modelship.configMapName" . }}
  labels:
    {{- include "modelship.labels" . | nindent 4 }}
data:
  models.yaml: |
    {{- .Values.models.config | nindent 4 }}
{{- end }}
