"""Tests for the profile -> models.yaml generator.

Mocks the budget reader (no Ray) and writes to tmp files. Asserts the rendered
yaml is valid, complete, resource-allocated within the ledger, and that the
refuse path writes nothing."""

from __future__ import annotations

from unittest.mock import patch

import pytest
import yaml

from modelship.deploy.profiles.budget import DeployBudget
from modelship.deploy.profiles.generator import generate_models_yaml
from modelship.deploy.profiles.selector import ProfileDoesNotFitError

_GiB = 1024**3


def _cpu(ram_gib: float, cores: float = 8.0) -> DeployBudget:
    return DeployBudget(cpu_units=cores, gpu_count=0, ram_bytes=int(ram_gib * _GiB), vram_bytes_per_gpu=0)


def _gpu(vram_gib: float, cores: float = 16.0, gpus: int = 1) -> DeployBudget:
    return DeployBudget(cpu_units=cores, gpu_count=gpus, ram_bytes=64 * _GiB, vram_bytes_per_gpu=int(vram_gib * _GiB))


def _generate(profile: str, budget: DeployBudget, path) -> dict:
    p = str(path / "models.yaml")
    with patch("modelship.deploy.profiles.generator.read_deploy_budget", return_value=budget):
        generate_models_yaml(profile, p)
    with open(p) as f:
        text = f.read()
    return {"text": text, "doc": yaml.safe_load(text)}


def test_chat_cpu_yaml_is_valid_and_complete(tmp_path):
    out = _generate("chat", _cpu(16), tmp_path)
    models = out["doc"]["models"]
    assert {m["usecase"] for m in models} == {"generate", "embed"}
    # every entry has the fields the deploy path needs
    for m in models:
        assert m["name"] and m["model"] and m["loader"]
        assert "num_cpus" in m and "num_gpus" in m
    assert out["text"].startswith("# Auto-generated by MSHIP_MODEL_STACK=chat")


def test_cpu_cores_sum_within_ledger(tmp_path):
    out = _generate("everything", _cpu(32, cores=8), tmp_path)
    total = sum(m["num_cpus"] for m in out["doc"]["models"])
    assert total <= 8.0 + 1e-6


def test_generate_anchor_gets_the_most_cores(tmp_path):
    models = _generate("everything", _cpu(32, cores=8), tmp_path)["doc"]["models"]
    by_uc = {m["usecase"]: m for m in models}
    gen_cpus = by_uc["generate"]["num_cpus"]
    assert gen_cpus == max(m["num_cpus"] for m in models)


def test_cpu_stack_requests_no_gpu(tmp_path):
    models = _generate("studio", _cpu(32), tmp_path)["doc"]["models"]
    assert all(m["num_gpus"] == 0 for m in models)
    # CPU image uses the stable_diffusion_cpp loader + its config block
    img = next(m for m in models if m["usecase"] == "image")
    assert img["loader"] == "stable_diffusion_cpp"
    assert "sample_steps" in img["stable_diffusion_cpp_config"]


def test_gpu_studio_shares_one_gpu_fractionally(tmp_path):
    models = _generate("studio", _gpu(24, gpus=1), tmp_path)["doc"]["models"]
    gpu_models = [m for m in models if m["num_gpus"] > 0]
    # generate (vllm) + image (diffusers) both on the GPU, footprint-weighted share
    assert {m["usecase"] for m in gpu_models} == {"generate", "image"}
    gen = next(m for m in models if m["usecase"] == "generate")
    img = next(m for m in models if m["usecase"] == "image")
    # the LLM (bigger footprint) gets the larger slice; shares cover the whole GPU
    assert gen["num_gpus"] > img["num_gpus"]
    assert abs(gen["num_gpus"] + img["num_gpus"] - 1.0) < 1e-6
    # num_gpus is the single sharing knob — the loader derives the VRAM cap from
    # it, so we must NOT also write gpu_memory_utilization (it would be clobbered).
    assert "gpu_memory_utilization" not in gen.get("vllm_engine_kwargs", {})
    # satellites stay on CPU
    emb = next(m for m in models if m["usecase"] == "embed")
    assert emb["num_gpus"] == 0


def test_gpu_studio_small_split_is_footprint_weighted(tmp_path):
    # studio-small on a 16 GiB card: 7B (6 GiB) + SD-Turbo (4 GiB) -> 0.6 / 0.4.
    models = _generate("studio", _gpu(15.3), tmp_path)["doc"]["models"]
    gen = next(m for m in models if m["usecase"] == "generate")
    img = next(m for m in models if m["usecase"] == "image")
    assert gen["num_gpus"] == 0.6
    assert img["num_gpus"] == 0.4


def test_multi_gpu_studio_allocates_whole_integer_gpus(tmp_path):
    # On a 2-GPU box the co-located models must each get a whole-integer num_gpus
    # (>= 1) — fractional num_gpus >= 1 is rejected by the config validator.
    out = _generate("studio", _gpu(24, gpus=2), tmp_path)
    gpu_models = [m for m in out["doc"]["models"] if m["num_gpus"] > 0]
    assert {m["usecase"] for m in gpu_models} == {"generate", "image"}
    for m in gpu_models:
        assert m["num_gpus"] >= 1 and m["num_gpus"] == int(m["num_gpus"])
    # 2 GPUs, 2 models -> one whole GPU each
    assert sum(m["num_gpus"] for m in gpu_models) == 2
    # the generated YAML must actually validate (this is where the old 1.4 crashed)
    from pydantic_yaml import parse_yaml_raw_as

    from modelship.infer.infer_config import ModelshipConfig

    parse_yaml_raw_as(ModelshipConfig, out["text"])


def test_multi_gpu_surplus_goes_to_largest_footprint(tmp_path):
    # 3 GPUs, 2 models: each gets 1, the surplus GPU goes to the larger (the LLM).
    models = _generate("studio", _gpu(24, gpus=3), tmp_path)["doc"]["models"]
    gen = next(m for m in models if m["usecase"] == "generate")
    img = next(m for m in models if m["usecase"] == "image")
    assert gen["num_gpus"] == 2
    assert img["num_gpus"] == 1


def test_gpu_chat_takes_whole_gpu(tmp_path):
    models = _generate("chat", _gpu(16, gpus=1), tmp_path)["doc"]["models"]
    gen = next(m for m in models if m["usecase"] == "generate")
    assert gen["num_gpus"] == 1.0
    # single GPU model → no forced gmu cap
    assert "gpu_memory_utilization" not in gen.get("vllm_engine_kwargs", {})


def test_refuse_path_writes_nothing(tmp_path):
    p = str(tmp_path / "models.yaml")
    with (
        patch("modelship.deploy.profiles.generator.read_deploy_budget", return_value=_cpu(8, cores=1)),
        pytest.raises(ProfileDoesNotFitError),
    ):
        generate_models_yaml("chat", p)
    import os

    assert not os.path.exists(p)


def test_generate_creates_missing_parent_dir(tmp_path):
    import os

    p = str(tmp_path / "does" / "not" / "exist" / "models.yaml")
    with patch("modelship.deploy.profiles.generator.read_deploy_budget", return_value=_cpu(16)):
        generate_models_yaml("chat", p)
    assert os.path.exists(p)
